spring:
  application:
    name: eurekaServer #내 애플리케이션 이름
  config:
    import: optional:configserver:http://localhost:8888

cloud:
  config:
    name: eurekaServer #config server에서 설정 파일을 가져올때 사용하는 이름

#config server에서 포트번호를 받아옴
server:
  port: ${server-port}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF