config:
  health-check: ${HEALTH_CHECK}

  jwt-secret: ${JWT_SECRET}

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info, prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    tags:
      application: gateway

resilience4j:
  circuitbreaker:
    instances:
      authCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3

      jobCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3

      coverLetterCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3

      correctionCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3

  timelimiter:
    instances:
      correctionCircuitBreaker:
        timeoutDuration: 120s    #타임아웃 시간 120초
        cancelRunningFuture: true

      coverLetterCircuitBreaker:
        timeoutDuration: 30s      # GPT 평균 응답
        cancelRunningFuture: true # 타임아웃 시 스레드 중단

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: authCircuitBreaker
                fallbackUri: forward:/fallback/auth

        - id: job-service
          uri: lb://job-service
          predicates:
            - Path=/job-service/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: jobCircuitBreaker
                fallbackUri: forward:/fallback/job

        - id: cover-letter-service
          uri: lb://cover-letter-service
          predicates:
            - Path=/cover-letter-service/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: coverLetterCircuitBreaker
                fallbackUri: forward:/fallback/cover-letter

        - id: correction-service
          uri: lb://correction-service
          predicates:
            - Path=/correction-service/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: correctionCircuitBreaker
                fallbackUri: forward:/fallback/correction