config:
  health-check: ${HEALTH_CHECK}

  jwt-secret: ${JWT_SECRET}

  redis-host: ${REDIS_HOST}
  redis-port: ${REDIS_PORT}

  mail-host: ${MAIL_HOST}
  mail-port: ${MAIL_PORT}
  mail-username: ${MAIL_USERNAME}
  mail-password: ${MAIL_PASSWORD}

  isDev: true

server:
  port: ${SERVER_PORT:8081}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DB_NAME}
    username: ${MYSQL_DB_USER}
    password: ${MYSQL_DB_PASSWORD}

  sql:
    init:
      mode: never

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 3000
            read-timeout: 3000

resilience4j:
  circuitbreaker:
    instances:
      JOB-SERVICE: # 호출 대상 서비스 명
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2

      COVER-LETTER-SERVICE: # 호출 대상 서비스 명
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
