config:
  health-check: ${health-check}

  jwt-secret: ${jwt-secret}

  redis-host: ${redis-host}
  redis-port: ${redis-port}

  mail-host: ${mail-host}
  mail-port: ${mail-port}
  mail-username: ${mail-username}
  mail-password: ${mail-password}

  isDev: false

server:
  port: ${SERVER_PORT:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    tags:
      application: auth

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/${mysql-db-name}?serverTimezone=Asia/Seoul
    username: ${mysql-db-user}
    password: ${mysql-db-password}

  sql:
    init:
      mode: never

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 3000
            read-timeout: 3000

resilience4j:
  circuitbreaker:
    instances:
      JOB-SERVICE: # 호출 대상 서비스 명
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2

      COVER-LETTER-SERVICE: # 호출 대상 서비스 명
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
