config:
  health-check: ${HEALTH_CHECK}

  jwt-secret: ${JWT_SECRET}

  redis-host: ${REDIS_HOST}
  redis-port: ${REDIS_PORT}

  job-secret: ${JOB_SECRET}

server:
  port: ${SERVER_PORT:8082}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    tags:
      application: job

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/${MYSQL_DB_NAME}?serverTimezone=Asia/Seoul
    username: ${MYSQL_DB_USER}
    password: ${MYSQL_DB_PASSWORD}
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000