config:
  health-check: ${HEALTH_CHECK}

  jwt-secret: ${JWT_SECRET}

  gpt-secret: ${GPT_SECRET}

server:
  port: ${SERVER_PORT:8084}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    tags:
      application: correction
      instance: ${INSTANCE_ID:unknown}

spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 3000
            read-timeout: 3000

resilience4j:
  circuitbreaker:
    instances:
      auth-service: # 호출 대상 서비스 명
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2

      cover-letter-service: # 호출 대상 서비스 명
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2